apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "*"
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nexus-operator
subjects:
  - kind: ServiceAccount
    name: nxrm-operator-certified
    namespace: SA_NAMESPACE
